apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaWE5oWW5KcGJEcG5hSEJmWkRoQ1NVTTNUazUxT0ZOQlUxSkxUMEo0VlRsMU1GazBZMDF0Y3poeU1GbHJjemd4IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHt9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcC5leGUiCn0K
type: kubernetes.io/dockerconfigjson
